M
My Workspace
New Blueprint

Search
Ctrl+
K

New


n
You are deploying from a Blueprint for Nellor02/swifthire
Blueprint Name
A unique name for your Blueprint.
Swift Hire Production
Branch
The repository branch with the render.yaml file.
Branch
main

Blueprint Path
The path to the Blueprint file in your repo (e.g., infra/render.yaml). Defaults to render.yaml at the root of your repository.
backend/render.yaml
Review Blueprint configurations from Nellor02/swifthire.
All future updates to your Blueprint file will be synced automatically, which may change your costs.
A Blueprint file was found, but there was an issue.

databases[0].plan
Legacy Postgres plans, including 'starter', are no longer supported for new databases. Update your database instance to a new plan in your render.yaml

services:
  - type: web
    name: swifthire-backend
    env: python
    plan: starter
    rootDir: backend
    buildCommand: ./build.sh
    startCommand: gunicorn config.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: "swifthire-backend.onrender.com"
      - key: DJANGO_CSRF_TRUSTED_ORIGINS
        value: "https://your-frontend-domain.vercel.app"
      - key: DJANGO_CORS_ALLOWED_ORIGINS
        value: "https://your-frontend-domain.vercel.app"
      - key: DJANGO_EMAIL_BACKEND
        value: "django.core.mail.backends.console.EmailBackend"
      - key: DJANGO_DEFAULT_FROM_EMAIL
        value: "noreply@swifthire.com"
      - key: DATABASE_URL
        fromDatabase:
          name: swifthire-db
          property: connectionString
databases:
  - name: swifthire-db
    plan: basic-256mb
Retry
0 services selected:

Move

