# Generated by Django 5.2.12 on 2026-04-15 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_application_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='employer_notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
