# Generated by Django 5.2.12 on 2026-04-14 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='seekerprofile',
            name='skills',
            field=models.TextField(blank=True, help_text='Comma-separated skills'),
        ),
        migrations.CreateModel(
            name='ShortlistedCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortlisted_candidates', to=settings.AUTH_USER_MODEL)),
                ('seeker_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortlisted_by', to='profiles.seekerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('employer', 'seeker_profile')},
            },
        ),
    ]
