# Generated by Django 5.2.13 on 2026-05-03 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='seekerprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/pictures/'),
        ),
    ]
