# Generated by Django 5.2.13 on 2026-05-05 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_seekerprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='target_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('message', 'Message'), ('application', 'Application'), ('status_update', 'Status Update'), ('shortlist', 'Shortlist'), ('contact', 'Contact'), ('system', 'System')], max_length=50),
        ),
    ]
